// Code generated by 'yaegi extract github.com/barab-i/incipio/internal/theme'. DO NOT EDIT.

package symbol

import (
	"github.com/barab-i/incipio/internal/theme"
	"reflect"
)

func init() {
	Symbols["github.com/barab-i/incipio/internal/theme/theme"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CurrentTheme":      reflect.ValueOf(&theme.CurrentTheme).Elem(),
		"DefaultTheme":      reflect.ValueOf(&theme.DefaultTheme).Elem(),
		"LoadThemeFromFile": reflect.ValueOf(theme.LoadThemeFromFile),

		// type definitions
		"Theme": reflect.ValueOf((*theme.Theme)(nil)),
	}
}
