// Code generated by 'yaegi extract github.com/charmbracelet/bubbles/key'. DO NOT EDIT.

package symbol

import (
	"github.com/charmbracelet/bubbles/key"
	"reflect"
)

func init() {
	Symbols["github.com/charmbracelet/bubbles/key/key"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewBinding":   reflect.ValueOf(key.NewBinding),
		"WithDisabled": reflect.ValueOf(key.WithDisabled),
		"WithHelp":     reflect.ValueOf(key.WithHelp),
		"WithKeys":     reflect.ValueOf(key.WithKeys),

		// type definitions
		"Binding":    reflect.ValueOf((*key.Binding)(nil)),
		"BindingOpt": reflect.ValueOf((*key.BindingOpt)(nil)),
		"Help":       reflect.ValueOf((*key.Help)(nil)),
	}
}
